server:
  env: production
  host: localhost
  port: 8000
  log_dir: ./logs

gateway:
  host: localhost
  port: 8007

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    db: pg_db

  redis:
    host: localhost
    port: 6379
    password: password
    db_number: 0
