version: '3.7'
services:
    postgresql:
        image: postgres:latest
        container_name: postgresql-kis-task
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pg_db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5342"
        volumes:
            - .postgresql:/var/lib/postgresql/data
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-kis-task
        depends_on:
            - postgresql
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        volumes:
          - .data_pgadmin:/var/lib/pgadmin
        ports:
          - "8001:80"
        networks:
            - postgres
        restart: unless-stopped

    # my-service:
    #     container_name: service
    #     build:
    #         context: ./
    #         dockerfile: Dockerfile
    #     ports:
    #         - "5001:5001"
    #     restart: always


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  data_pgadmin:

