version: '3'

services:
    postgresql:
        image: postgres:15-alpine
        container_name: postgresql-kis-task
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=pg_db
          - POSTGRES_PORT=5432
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - .postgresql:/var/lib/postgresql/data
        networks:
            - postgres
        restart: unless-stopped

    redis:
      image: redis:latest
      container_name: redis-kis-task
      ports:
        - "6379:6379"
      volumes:
        - .redisdata:/data
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      networks:
        - redis

    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus-kis-task
      volumes:
        - prometheus:/etc/prometheus/
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      hostname: prometheus
      command:
        - --config.file=/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      restart: unless-stopped
      environment:
        TZ: "Europe/Moscow"
      networks:
        - prometheus

    my-service:
        container_name: service
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
          - "8000:8000"
          - "7071:7071"
          - "8007:8007"
        environment:
          - CONFIG_PATH=/app/config.yaml
        volumes:
          - ./config.yaml:/app/config.yaml
        restart: unless-stopped
        networks:
          - postgres
          - redis
        depends_on:
          - postgresql
          - prometheus
          - redis


networks:
  postgres:
    driver: bridge
  prometheus:
    driver: bridge
  redis:
    driver: bridge

volumes:
  postgres:
  redis:
  prometheus:

