version: "3"

tasks:
  run-local:
    cmds:
      - go run main.go --config_path=./config.yaml

  run-migrations:
    cmds:
      - go run cmd/migrator/main.go

  build-container:
    cmds:
      - docker build ./ -t kis-blog-backend
    silent: false

  run-container:
    cmds:
      - docker run -p 5000:5000 -it kis-blog-backend
    silent: false

  generate:
    cmds:
      - protoc
        --proto_path ./proto/googleapis
        --proto_path ./proto/grpc-gateway
        --proto_path ./proto
        --go_out=./internal/gen/
        --go_opt=paths=source_relative
        --go-grpc_out=./internal/gen/
        --go-grpc_opt=paths=source_relative
        --grpc-gateway_out=./internal/gen/
        --experimental_allow_proto3_optional
        --grpc-gateway_opt=paths=source_relative,allow_delete_body=true
        --openapiv2_out=allow_merge=true,allow_delete_body=true,merge_file_name=blogService:./proto/api/
        service.proto swagger.proto